# Generated by Django 4.0.4 on 2022-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazine_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='magazine_details',
        ),
    ]
