# Generated by Django 4.0.4 on 2022-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_magazine_upload_delete_magazine_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Ajay')),
                ('file_name', models.CharField(max_length=25)),
                ('discription', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('rent_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('system_category', models.CharField(max_length=25)),
                ('magazine_category', models.CharField(max_length=25)),
            ],
        ),
    ]
