# Generated by Django 4.0.4 on 2022-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_magazine_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine_upload',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
