# Generated by Django 4.0.4 on 2022-05-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_remove_magazine_details_magazine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine_details',
            name='id',
        ),
        migrations.AddField(
            model_name='magazine_details',
            name='magazine_id',
            field=models.IntegerField(default=23, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine_upload',
            name='magazine_id',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='meg_id', to='upload.magazine_details'),
            preserve_default=False,
        ),
    ]
