# Generated by Django 4.0.4 on 2022-05-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_remove_magazine_details_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazine_category',
            fields=[
                ('category_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=25)),
                ('category_discription', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='magazine_details',
            name='magazine_category',
        ),
        migrations.RemoveField(
            model_name='magazine_details',
            name='system_category',
        ),
        migrations.AddField(
            model_name='magazine_details',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='meg_id', to='upload.magazine_category'),
            preserve_default=False,
        ),
    ]
